# Generated by Django 3.0.14 on 2023-04-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], default='IN_TRANSIT', max_length=11)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('REGULAR', 'Regular')], default='REGULAR', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(max_length=255)),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.CargoType')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('end_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_port', to='project_app.Port')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_port', to='project_app.Port')),
            ],
        ),
        migrations.CreateModel(
            name='CostCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('shipment_cost', models.FloatField()),
                ('tax', models.TextField()),
                ('currency_rate', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.CargoType')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.User')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Container')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Port')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='end_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_container', to='project_app.Port'),
        ),
        migrations.AddField(
            model_name='container',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Shipment'),
        ),
        migrations.AddField(
            model_name='container',
            name='start_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_container', to='project_app.Port'),
        ),
    ]
