# Generated by Django 3.0.14 on 2023-05-07 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('departure_date', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('arrival_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], default='IN_TRANSIT', max_length=11)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Booking')),
            ],
        ),
        migrations.RemoveField(
            model_name='containerlocation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='containerlocation',
            name='container',
        ),
        migrations.RemoveField(
            model_name='containerlocation',
            name='port',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_port',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_port',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='cargo_type',
        ),
        migrations.RenameField(
            model_name='cargotype',
            old_name='name',
            new_name='cargo_type_name',
        ),
        migrations.RemoveField(
            model_name='costcalculation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='costcalculation',
            name='currency_rate',
        ),
        migrations.RemoveField(
            model_name='costcalculation',
            name='shipment',
        ),
        migrations.AddField(
            model_name='faq',
            name='query_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_groups', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='ContainerLocation',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.AddField(
            model_name='track',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.CargoType'),
        ),
        migrations.AddField(
            model_name='track',
            name='end_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_port', to='project_app.Port'),
        ),
        migrations.AddField(
            model_name='track',
            name='start_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_port', to='project_app.Port'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_address', to='project_app.User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to='project_app.User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cargo_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.CargoType'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_port', to='project_app.Port'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pick_up_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_port', to='project_app.Port'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project_app.User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.CostCalculation'),
        ),
    ]
