# Generated by Django 3.0.14 on 2023-05-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20230507_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='query_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
