# Generated by Django 3.0.14 on 2023-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_auto_20230508_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_phone',
            field=models.CharField(max_length=20),
        ),
    ]
