# Generated by Django 3.0.14 on 2023-05-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_auto_20230509_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='Customer',
            new_name='user',
        ),
    ]
