# Generated by Django 3.0.14 on 2023-05-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0012_auto_20230509_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], default='IN_TRANSIT', max_length=11)),
                ('expected_arrival_date', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Booking')),
            ],
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
