# Generated by Django 3.0.14 on 2023-05-09 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0015_auto_20230509_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 22, 23, 23, 29429)),
        ),
    ]
