# Generated by Django 3.0.14 on 2023-05-09 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0016_auto_20230509_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglog',
            old_name='booking',
            new_name='booking_order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 22, 33, 2, 155118)),
        ),
    ]
