# Generated by Django 3.0.14 on 2023-05-09 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0018_auto_20230509_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costcalculation',
            old_name='shipment_cost',
            new_name='base_shipment_cost',
        ),
        migrations.RemoveField(
            model_name='costcalculation',
            name='cargo_type',
        ),
        migrations.AlterField(
            model_name='cargotype',
            name='cargo_type_name',
            field=models.CharField(choices=[('Shipper', 'SHIPPER'), ('Warehousing', 'WAREHOUSING'), ('Accessorial', 'ACCESSORIAL'), ('Blind shipment', 'BLIND SHIPMENT'), ('Embargo', 'EMBARGO')], default='none told', max_length=20),
        ),
        migrations.AlterField(
            model_name='costcalculation',
            name='tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 23, 38, 5, 991478)),
        ),
    ]
