# Generated by Django 3.0.14 on 2023-05-10 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0021_auto_20230510_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tax',
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 0, 7, 17, 958013)),
        ),
    ]
