# Generated by Django 3.0.14 on 2023-05-10 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0025_auto_20230510_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 2, 38, 20, 320619)),
        ),
    ]
