# Generated by Django 3.0.14 on 2023-05-10 02:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0026_auto_20230510_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tax',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='project_app.CostCalculation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='weight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_weight', to='project_app.CostCalculation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 2, 43, 3, 627698)),
        ),
    ]
