# Generated by Django 3.0.14 on 2023-05-10 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0028_auto_20230510_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tax',
        ),
        migrations.AlterField(
            model_name='booking',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 2, 56, 52, 770904)),
        ),
        migrations.DeleteModel(
            name='CostCalculation',
        ),
    ]
