# Generated by Django 3.0.14 on 2023-05-10 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0029_auto_20230510_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 3, 9, 7, 632820)),
        ),
    ]
