# Generated by Django 3.0.14 on 2023-05-13 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0030_auto_20230510_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 20, 53, 37, 498396)),
        ),
    ]
