# Generated by Django 4.2.3 on 2023-12-04 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0031_auto_20230513_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 3, 15, 15, 683779)),
        ),
    ]
