# Generated by Django 4.2.3 on 2023-12-04 04:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0034_alter_bookinglog_id_alter_cargotype_id_alter_faq_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cell_phone',
            field=models.CharField(default='Null', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 4, 16, 48, 931008)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='project_app.user'),
        ),
    ]
