# Generated by Django 4.2.3 on 2023-12-07 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0039_alter_order_expected_arrival_date_portlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='portlog',
            name='operation_type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 53, 41, 379994)),
        ),
    ]
