# Generated by Django 4.2.3 on 2023-12-07 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0041_alter_order_expected_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 10, 2, 51, 237031)),
        ),
        migrations.AlterField(
            model_name='portlog',
            name='Port_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.port'),
        ),
    ]
